## Forward Propogation in Neural Networks

In [21]:
import numpy as np

In [22]:
X = np.array([[0,0],[0,1],[1,0],[1,1]]) # AND Function
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [23]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [24]:
def derivativeSig(z):
    return sig(z)*[1 - sig(z)]

In [40]:
# Initialize weights
# Only 1 output layer, no hidden layer
weights = 2 * np.random.random((2, 1)) - 1 # w1 and w2 bw -1 and 1
bias = 2 * np.random.random(1) - 1
lr = 0.1
weights, bias

(array([[-0.46188229],
        [-0.23194813]]), array([-0.65734896]))

In [41]:
for iter in range(10000):
    output0 = X
    # Calculate the output using sigmoid as activation function
    # sigmoid(weights*x matrix plus the bias)
    output = sig(np.dot(output0, weights) + bias)

    # Once we have the output we do back prop
    first_term = output - Y # Explained by sir in video
    input_for_last_layer = np.dot(output0, weights) + bias
    second_term = derivativeSig(input_for_last_layer)
    first_two = first_term * second_term
    first_two = first_two.reshape(4,1)
    #print(first_two.shape, first_two)

    changes = np.array([[0.0], [0.0]])

    # Multiply 3rd part of derivative to the first_two
    for i in range(2):
        for j in range(4):
            changes[i][0] += first_two[j][0] * output0[j][i]

    # Update weights
    weights = weights - lr*changes
    bias_change = 0.0
    for j in range(4):
        bias_change += first_two[j][0] * 1
    bias = bias - lr * bias_change

output = sig(np.dot(X, weights) + bias)
weights, bias, output

(array([[5.47522617],
        [5.47522617]]), array([-8.30555005]), array([[2.47080303e-04],
        [5.57073582e-02],
        [5.57073580e-02],
        [9.33696100e-01]]))

In [42]:
# VECTORIZED
for iter in range(10000):
    output0 = X
    # Calculate the output using sigmoid as activation function
    # sigmoid(weights*x matrix plus the bias)
    output = sig(np.dot(output0, weights) + bias)

    # Once we have the output we do back prop
    first_term = output - Y # Explained by sir in video
    input_for_last_layer = np.dot(output0, weights) + bias
    second_term = derivativeSig(input_for_last_layer)
    first_two = first_term * second_term
    first_two = first_two.reshape(4,1)
    #print(first_two.shape, first_two)

    changes = np.dot(output0.T, first_two)
    # Update weights
    weights = weights - lr*changes
    bias_change = np.sum(first_two)
    bias = bias - lr * bias_change

output = sig(np.dot(X, weights) + bias)
weights, bias, output

(array([[6.27142802],
        [6.27142802]]), array([-9.49696315]), array([[7.50738529e-05],
        [3.82160181e-02],
        [3.82160181e-02],
        [9.54604880e-01]]))

## 1 Hidden Layer with 2 units

In [11]:
weights_hidden = 2 * np.random.random((2, 2)) - 1 
biases_hidden = 2 * np.random.random((1, 2)) - 1
weights_output = 2 * np.random.random((2 , 1)) - 1
bias_output = np.random.random((1, 1)) - 1

In [12]:
output0 = X
outputHidden = sig(np.dot(output0, weights_hidden) + biases_hidden)
output = sig(np.dot(outputHidden, weights_output) + bias_output)
output

array([[0.62256208],
       [0.65861304],
       [0.58432247],
       [0.62099819]])